### ISSUE TITLE
Report Issue - featurePictureBox not showing map image

### ISSUE THREAD

**Issue by JakeBrownPDX** [geocortex/vertigis-reporting-client-py#11]
I'm having trouble with featurePictureBox populating a map image.  The rest of my report attribute data populates fine. The featurePictureBox displays fine in report preview mode.  The web map the feature picture box uses is available to the whole enterprise.

Any ideas?

**Comment by rcooney** [comment]
The Designer preview and the Python client both use the same REST API to generate the report. The only differences that I can think of that might affect the behaviour are:
- The Designer preview is able to supply the current report layout on the request (with any unsaved edits), where as the Python client will used the last saved version of the report layout.
- The Designer preview will always supply an access token, the Python client only will do this if you explicitly supply one.

**Comment by JakeBrownPDX** [comment]
@rcooney  if I point to a public web map it works fine, map drops into report.  solid workaround.  If you know how I can explicitly pass in a token for the featurePictureBox  I would.  Seems like that should be baked into next version though :)

**Comment by JakeBrownPDX** [comment]
@rcooney   

> * The Designer preview will always supply an access token, the Python client only will do this if you explicitly supply one.

any guidance on how to do this?

**Comment by rcooney** [comment]
@JakeBrownPDX the token is supplied to the report **as a whole** by using `token=` parameter on the `run` method:
```
url = await run("itemId", token="eyJhbGciOiJIUzI1Ni...")
```

There isn't a way to target a different tokens for different purposes in a report. For example, you cannot supply a token to be used with a specific FeaturePictureBox. You can supply just the one token and if the token is appropriate to use to access a resource like a map or layer then the report engine will apply it automatically.

Very much related to this... it is not possible to have a report that a user can run anonymously, but then also have the report include a map image that accesses secured content (like a web map shared with your organization).

**Comment by JakeBrownPDX** [comment]
@rcooney cool, just making sure there was only one token.  My web map is shared with organization so the token I'm using should have access.   I'm running using a token "grant_type": "client_credentials"  using a methodology I found here:  https://developers.arcgis.com/labs/rest/get-an-access-token/

It doesn't seem like there should be a problem with the token as it has access to report and the web map is shared with org.

**Comment by rcooney** [comment]
@JakeBrownPDX is the token for the same user that you are signed in to designer as?

**Comment by BDS-Maps** [comment]
@rcooney  when I sign into report designer, I sign in as a user.  

When I generate a token with the python script, I use a client_id and client secret of portal app.  I tried creating a dedicated python scripting app and I've tried using the app I used in the geocortex reporting post install.

I'm running using a token "grant_type": "client_credentials" using a methodology I found here: https://developers.arcgis.com/labs/rest/get-an-access-token/

**Comment by rcooney** [comment]
I would suggest taking that access token and confirming in a web browser that it have does indeed have access to both the report item and the web map. The URL to test those will be something like this:
```
https://server/portal/sharing/rest/content/items/<YOUR_ITEM_ID>?f=pjson&token=<YOUR_TOKEN>
```

Can you also confirm whether the web map contains any layers/services that are secured. If it does contain secured content then the access token would have to be valid for those resources as well.

**Comment by JakeBrownPDX** [comment]
You're right @rcooney   the client_id/secret token did not have access to web map. 

message: "You do not have permissions to access this resource or perform this operation.",

The web map is shared with enterprise, we don't have anything on our portal that is public.  It contains public services, just a base map layer.

I'm wondering if I'm running into a limitation of application generated tokens.

**Comment by rcooney** [comment]
Ahh yes. See https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/limitations-of-application-authentication/.

Hmmm.

**Comment by JakeBrownPDX** [comment]
@rcooney any ideas?

**Comment by rcooney** [comment]
Hi @JakeBrownPDX, 

I think you've got two options:
- Move this Python to an ArcGIS Jupyter Notebook and use the code suggested here https://github.com/geocortex/vertigis-reporting-client-py/issues/8#issuecomment-719824270 to access the token.
- Since your web map item doesn't actually reference any secured content... you could create an equivalent public web map in ArcGIS Online and point your report at it instead of the secured web map in your portal.

**Comment by JakeBrownPDX** [comment]
@rcooney   I'm not sure option 1 will work for this application, but I'll admit I have not yet been using jupyter notebooks.  We have the latest version of portal installed not and can support to module.

For option 2 that would work, but I could use a tip on how to include the map url.  my report "select a map chooser" is wired to portal.  and produces results like this:  https://www.portlandmaps.com/portal#33ea4550c8144e66847d902e4766c2f7   which seems to be a specialized format.   

The public AGOL web map I can use is this: [https://pdx.maps.arcgis.com/home/item.html?id=23807511a7f5417395671d18e591fd96](https://pdx.maps.arcgis.com/home/item.html?id=23807511a7f5417395671d18e591fd96)    but when I include that in the feature picture box properties for "map" and run a preview it comes back blank.  Should I be changing that format?

Appreciate your help.  Hopefully this thread is helpful to others too.

**Comment by rcooney** [comment]
@JakeBrownPDX for option 2 you can just paste in `https://pdx.maps.arcgis.com#23807511a7f5417395671d18e591fd96`.

This custom format leaves a bit to be desired. The team was just having a discussion today about supporting the standard item URL format.

**Comment by JakeBrownPDX** [comment]
@rcooney   that worked great! I am able to generate reports that include feature maps.  Thanks for all the help Ryan!
