### ISSUE TITLE
Syntax for multiple input parameters

### ISSUE THREAD

**Issue by JakeBrownPDX** [geocortex/vertigis-reporting-client-py#13]
Hello, wondering what the syntax is for multiple report parameters or if that's supported

USER =  "Jake Brown", DB = "DEV"

**Comment by rcooney** [comment]
Hi Jake,

Yes. What you have there should work. 

The last parameter of the `run` method is a `**kwargs**` parameter, which means it accepts a list of additional arbitrary `key=value` parameters. We take these extra parameters and use them as the input parameters of the report. The `key` just needs to match the name of the parameter in the report.

**Comment by JakeBrownPDX** [comment]
oh indeed - I was overly focused on JSON.  Thanks @rcooney

**Comment by JakeBrownPDX** [comment]
oh indeed - I was overly focused on JSON.  Thanks @rcooney
