### ISSUE TITLE
Configuring to run as a schedule task

### ISSUE THREAD

**Issue by JakeBrownPDX** [geocortex/vertigis-reporting-client-py#8]
Hello, I was hoping to create a scheduled task that would kick of a script from my windows server.  I am running python 3.6 that is included with pro from the command line.  The report exists on our portal.  I'm am having trouble with asyncio, just basically new to it and could use a tip.  

```py
import arcpy,base64,requests,json
import asyncio
from geocortex.reporting.client import run

Portal_UserName = ""
Portal_Password = ""

Token_URL = 'https://www.portlandmaps.com/portal/sharing/rest/generateToken'  
payload  = {'username' : Portal_UserName,'password' : Portal_Password,   'referer' : 'www.portlandmaps.com', 'f' : 'json' }  
token_response = requests.post(Token_URL, data=payload)  
token =json.loads (token_response.text)
aToken = token['token']

async def runReport():
    url = await run("ae382b7c21ee477fb8a48f9cf54fa9dd", portal_url="https://www.portlandmaps.com/portal", token=aToken,folder_rsn=[4548605])
    print(url)

loop = asyncio.get_event_loop()
loop.run_until_complete(runReport())
```

**Comment by JakeBrownPDX** [comment]
token should be good, I'm printing it and it looks legit.  

I'm getting different error now: 

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.portlandmaps.com/apps/gcx/report/Geocortex/Reporting/service/auth/token/run

the URL looks good...

**Comment by JakeBrownPDX** [comment]
FYI - my portal token was generated by account that owns the report item.

**Comment by JakeBrownPDX** [comment]
I only have 1 version of python installed on this machine

**Comment by ianschmitz** [comment]
You are likely encountering issues by using the `generateToken` endpoint with username and password. They want either a `referer` or IP, neither of which will be reliable in this use case i don't believe. See https://developers.arcgis.com/rest/users-groups-and-items/generate-token.htm. `referer` is a browser header, and won't be sent by our Python API nor the Reporting backend. IP will likely also not be reliable as the IP between the machine running the Python script which makes requests to Portal, as well as the IP for the Reporting backend are likely different.

For authentication with Reporting we suggest you use the OAuth 2.0 flow. We have had issues in past with token security using the older `generateToken` endpoint and have switched to OAuth. Portal's OAuth app login flow is more suitable for this sort of use case. Take a look at https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/accessing-arcgis-online-services/ for information on how to register the item in your Portal, as well as sample Python code to generate a token.

If running from an ArcGIS Notebook, it can potentially be even simpler:

```py
!pip install geocortex-reporting-client

from arcgis.gis import GIS
from geocortex.reporting.client import run 

gis = GIS("home")

report = await run("<itemid>", token=gis._con.token FeatureIds=[1])
print(report)
```

Note that i'm not sure if `gis._con.token` is officially supported, although it has been suggested on their forums: https://community.esri.com/thread/211185-get-the-token-using-arcgis-python-api

**Comment by ianschmitz** [comment]
I've filed #10 for us to improve some of the error messaging to make these types of errors easier to debug 😃

**Comment by JakeBrownPDX** [comment]
yep that worked great.  Thanks @ianschmitz 

I found another link that may be helpful to others:
https://developers.arcgis.com/labs/rest/get-an-access-token/
